[server]
url = "localhost:3000"
external_url= "http://localhost:3000"
name = "Resubnance" # for display purposes only

[subsonic]
url = "https://navidrome.instance.com"
username = "admin"
password = "admin"
caching_strategy = { DiskCache = { path = "/tmp/resubnance", min_cache_before_play = 10240 } }

[audio]
buffer_size = 4096    # adjust to your sound card
sampling_rate = 44100 # check if your sound card supports that
